exp-models/addon/adapters/experiment.js
exp-models/addon/models/experiment.js

- update the default query url for the experiment page so that it is not using elastic search
- add necessary fields to experiment model
- active (possibly change to status?) can be 'Active', 'Draft', or 'Archive'
- is date the proper type for `endDate`, `beginDate`, and `lastEdited`

update default url param and model

---

exp-models/addon/adapters/experiment.js
exp-models/addon/mixins/jam-document-adapter.js
exp-models/addon/mixins/jam-serializer.js
exp-models/addon/models/profile.js
exp-models/addon/models/session.js
exp-models/addon/serializers/session.js

Intended as companion to https://github.com/CenterForOpenScience/experimenter/pull/17
Refs https://openscience.atlassian.net/browse/LEI-42
Various changes to session model, needed to support related PR.
- DS.store should be DS.attr (fixes issue causing ember inspector to crash)
- Field name and relationship changes
- Apply query fix to all document records
- Add ability to track a text "<relationAttr>Id" field to a record, for any constructed records. Should save an API call when we want title of a related record.

Fix issues with session record

---

exp-models/app/instance-initializers/exp-models.js

Refs https://openscience.atlassian.net/browse/LEI-78
Companion to https://github.com/CenterForOpenScience/experimenter/pull/31
Move "gloval app reference" into instance initializer for addon (rather than in the consuming app, eg "experimenter")., Then all apps using models will be able to register new models dynamically,without needing to add boilerplate.
https://github.com/CenterForOpenScience/experimenter/pull/31#discussion_r53316677

Move initializer into exp-models

---

exp-models/addon/models/account.js
exp-models/addon/models/experiment.js
exp-models/addon/serializers/account.js
exp-models/addon/transforms/profiles.js
exp-models/addon/utils/eligibility.js
exp-models/app/transforms/profiles.js
exp-models/tests/unit/transforms/profiles-test.js

Changes:
- Add eligibility.js utils for parsing and checking eligibility
- Make account.profiles computed to allow transformation into a genuine Ember.Object subclass
- Add 'age' computed to Profile class

Add eligibility helpers

---

exp-player/addon/components/exp-audioplayer.js
exp-player/addon/components/exp-consent.js
exp-player/addon/components/exp-frame-base.js
exp-player/addon/components/exp-video.js

Refs https://openscience.atlassian.net/browse/LEI-88
Tracking PR; see checklist for status.
Fix issues of shared and lingering state in the experimenter player.
- It appears that `willDestroyElement` is not called either. Speculatively, it seems that the *same* component is getting new parameters; rather than creating a second new instance of the same type.
- Make sure that init creates instance variables for  `meta.data` (things to be serialized), in addition to the vars already added for `meta.parameters` (things to control config of page)

Fix state and component transition issues

---

exp-player/addon/components/exp-audioplayer.js
exp-player/addon/components/exp-video.js
exp-player/addon/mixins/media-reload.js
exp-player/tests/unit/mixins/media-reload-test.js

Refs [#LEI-93]
Fixes an issue where when two video or sound frames appeared in a row, the media clip from the second frame would not display correctly.
(Eg, the second frame would show the video from frame 1, and the time bar would be at the end, not the start)
All components that use media will need to extend with this mixin.

Force media elements to reload

---

exp-models/addon/mixins/jam-document-adapter.js
exp-models/addon/models/account.js
exp-models/addon/services/current-user.js
exp-models/app/services/current-user.js
exp-player/addon/components/exp-exit-survey.js
exp-player/addon/components/exp-frame-base.js
exp-player/addon/components/exp-player.js
exp-player/addon/mixins/exp-player-route.js
exp-player/addon/templates/components/exp-player.hbs
exp-player/tests/unit/mixins/exp-player-route-test.js

Use a route mixin to make the exp-player route load until all of the
needed data is ready and successfully saved. This allows us to leverage
the loading substate of that route to give better feedback to the user,
and give better confidence that once the player is loaded it has
everything it needs to run.

A better way of fetching past sessions?

---

exp-player/addon/components/exp-exit-survey.js
exp-player/addon/styles/components/exp-mood-questionnaire.scss

Refs: https://openscience.atlassian.net/browse/LEI-140
Move the date picker so that it doesn't go off the top of the screen.
Remove duplicate page title.
Place the date picker below the field instead of above.
Remove title and description from form schema.
Previous:
Current:
The date picker should be completely on the page.

[Feature] move datepicker to bottom of field and remove duplicate page title

---

exp-models/addon/services/current-user.js
exp-player/addon/components/exp-exit-survey.js
exp-player/addon/components/exp-frame-base.js

Refs: https://openscience.atlassian.net/browse/LEI-160
Companion to: https://github.com/CenterForOpenScience/lookit/pull/44
Fix small issues with lookit + newest codebase.
This should fix adapter errors that occur when trying to participate in an experiment via lookit. (due to the current user service requesting `experimenter.accounts.experimenter.accounts.tester0` or such).
At the end of the experiment, you should now be able to opt out of emails, and have data submit to server. Previously, due to the lack of a default value, this resulted in errors of "Uncaught TypeError: Cannot set property 'emailOptOut' of undefined" being dumped to the console. (which prevented the value from being sent)

Support Lookit + revised URLs

---

exp-player/addon/components/exp-frame-base.js
exp-player/addon/components/exp-player.js
exp-player/addon/templates/components/exp-player.hbs

Refs: https://openscience.atlassian.net/browse/LEI-161
Companion to: None
Fix issue with frames not setting state correctly
Fix issue with sequence of frames saving frameIDs twice
Return to fullscreen button should be on top of page, not underneath a big item (maximize visibility)
This fixes an issue where you had to play sound twice to advance frames, as well as issues with the `sequence` property of sessions saved to the server.

Fix broken frames

---

exp-player/addon/components/exp-video-consent.js
exp-player/addon/components/exp-video-physics.js
exp-player/addon/components/exp-video-preview.js
exp-player/addon/components/exp-video-record.js
exp-player/addon/mixins/video-id.js
exp-player/tests/unit/mixins/video-id-test.js

We had different representations of videoId across different components. Using a mixin helps enforce consistent naming conventions.

Unify videoId implementations in VideoId mixin

---

exp-player/addon/components/exp-exit-survey.js
exp-player/addon/templates/components/exp-exit-survey.hbs

This adds conditional logic to the template to show a different message based on whether or not the user has opted to share their content on Databrary.

Add conditional databrary message to video privacy

---

exp-models/addon/services/current-user.js

Required for ISP logins to work: https://github.com/CenterForOpenScience/isp/pull/23
If a profile for an account is undefined, return a fake profile instead of throwing an error.

Update current-user to handle no profile

---

exp-player/addon/components/exp-consent.js
exp-player/addon/components/exp-isp-consent/component.js
exp-player/addon/components/exp-isp-consent/template.hbs
exp-player/addon/templates/components/exp-consent.hbs
exp-player/app/components/exp-isp-consent.js

Add exp-frame for ISP consent from
- Make `exp-consent` form button text a variable 
- Add `exp-isp-consent` exp-frame that extends `exp-consent.js` and defines 
additional properties
- `exp-isp-consent/template.hbs` includes translation helpers

Feature: ISP consent form

---

exp-player/addon/components/exp-card-sort/template.hbs
exp-player/addon/styles/addon.scss
exp-player/addon/styles/components/exp-card-sort.scss

The neutral bucket label in the second qsort is longer than the others and throws off the bucket positioning:  
- Add padding to the other labels so that the buckets line up. 
- Also add card-sort css to exp-addon/styles

Fix qsort bucket labels

---

exp-player/addon/components/exp-free-response/component.js
exp-player/addon/components/exp-free-response/template.hbs

If a user has an odd profileId, ask them to describe what they were doing at 7pm and if it is even ask what they were doing at 10am.
Add computed properties to replace "##" in the translation strings with the correct translated time.
Requires changes to `en-us/translations.js`(needs variables for 10am & 7pm and ## instead of the hard-coded times), so https://github.com/CenterForOpenScience/isp/pull/32 should be merged first :octocat:

Alternate times in free response questions

---

exp-player/addon/components/exp-card-sort/template.hbs
exp-player/addon/components/exp-free-response/component.js

Since numbers do not need to be translated, remove any translation helpers for the number variables where possible.
- Do not translate number of remaining cards in `exp-card-sort` template
- Do not translate remaining characters in `exp-free-response` component

Remove unnecessary number variables

---

exp-player/addon/components/exp-free-response/component.js
exp-player/addon/components/exp-overview/component.js
exp-player/addon/components/exp-rating-form/component.js

- The exp-overview and exp-rating-form components serialize the data into objects, so meta.data.type should be 'object' not 'string'
- Check for undefined values in exp-free-response

Feature: Schema fixes

---

exp-models/addon/services/current-user.js
exp-player/addon/components/exp-free-response/component.js

- Fix getting participantID in free response form
- Make test profileId accountUsername.accountUsername 
Note: Requires https://github.com/CenterForOpenScience/isp/pull/41 to be merged first

Fix getting participantID in free response form

---

exp-player/addon/components/exp-card-sort/template.hbs
exp-player/addon/components/exp-free-response/component.js
exp-player/addon/components/exp-free-response/template.hbs
exp-player/addon/components/exp-overview/component.js
exp-player/addon/components/exp-overview/template.hbs

To make testing the survey quicker, remove form validation checks so that the entire survey does not have to be completed each time.

Remove form validation to facilitate testing

---

exp-player/addon/components/exp-overview/template.hbs
exp-player/addon/components/exp-rating-form/template.hbs
exp-player/addon/components/isp-radio-group/component.js
exp-player/addon/components/isp-radio-group/template.hbs
exp-player/app/components/isp-radio-group/component.js
exp-player/tests/integration/components/isp-radio-group/component-test.js

After the ISP `radio-group` component is renamed to `isp-radio-group` in https://github.com/CenterForOpenScience/isp/pull/38, the overview and rating form components in exp-addons needs to use the `isp-radio-group` component instead of the `radio-group` component.

Move isp-radio-group component to exp-addons [EOSF-151]

---

exp-player/addon/components/exp-rating-form/component.js
exp-player/addon/components/exp-rating-form/template.hbs
exp-player/addon/helpers/add.js
exp-player/app/helpers/add.js
exp-player/tests/unit/helpers/add-test.js

Make it easier for participants to take the survey by splitting up the rating-form into multiple pages.
- Add page to each question, and in the template only show the question if it's page equals the `currentPage`.
- Make `generateSchema` expect an object with parameters so that it is easier to tell what is getting passed in.
Requires https://github.com/CenterForOpenScience/isp/pull/48 and https://github.com/CenterForOpenScience/isp/pull/49 to be merged

Feature/paginate rating form [EOSF-153]

---

exp-player/addon/components/exp-thank-you/component.js
exp-player/addon/components/exp-thank-you/template.hbs

Make it possible to pass in urls for the exit and results page, making it easier to change them if the routes change.
Specify the `exitUrl` and `resultsUrl` as parameters in the `exp-thank-you` component.

Make exit and results url frame parameters

---

exp-player/addon/components/exp-frame-base.js
exp-player/addon/components/exp-rating-form/component.js

Currently, when a user scrolls to the bottom of an exp-frame and hits continue, the scroll position remains the same in the next frame and the user must manually scroll to the top to view the beginning of the form.
When a user scrolls to the bottom of the page and hits continue to move on to the next frame, use `window.scrollTo(0,0)` so that the user sees the top of the frame first.

Scroll to top of next frame [LEI-185]

---

exp-player/addon/components/exp-rating-form/component.js

The first and last radio buttons in measure 6, item 1 were spaced further away from the rest:  
Even out the spacing between the radio buttons by setting a max-width:

Fix radio button spacing in measure 6, item 1 [LEI-195]

---

exp-models/addon/models/account.js

Fix getting past sessions
- Filter sessions by `profile.profileId`, instead of `profile.id`
- If profileId is undefined, remove the query parameter instead of filtering by `*`

Fix getting past sessions from profileId

---

exp-player/addon/components/exp-overview/component.js
exp-player/addon/components/exp-overview/template.hbs

Purpose
-------
On the exp-overview form, if a user answers yes to question 8: "Do you follow a religion"
show question 9: "If so, which one do you follow?" Otherwise, hide it.
Changes
-------
Add a computed property `showOptional` that watches the value of question 8. Then in the template, only show that question if `showOptional` is true.

Hide optional overview form question [LEI-192] 

---

exp-player/addon/components/exp-rating-form/component.js
exp-player/addon/components/exp-rating-form/template.hbs

In order for experiment data to show up in experimenter, the session must get marked as completed. 
Mark the session as completed after the user finishes the last survey page.

Mark session as completed

---

exp-player/addon/components/exp-video-preview.js
exp-player/addon/randomizers/pref-phys-pilot.js

Video recording wasn't working in exp-video-preview (when we show the parent the stimuli and want to be able to check the baby *isn't* watching); added back based on exp-video-physics (tested locally)

Add video recording back to exp-video-preview

---

exp-player/addon/components/exp-card-sort/template.hbs
exp-player/addon/components/exp-free-response/template.hbs
exp-player/addon/components/exp-rating-form/template.hbs

Use translation string `'global.previousLabel'` for "Previous Page" button label so that it will get translated if the selected language changes.

Use translation string for "Previous Page"

---

exp-player/addon/components/exp-card-sort/component.js
exp-player/addon/components/exp-frame-base.js
exp-player/addon/components/exp-free-response/component.js
exp-player/addon/components/exp-overview/component.js
exp-player/addon/components/exp-player.js
exp-player/addon/components/exp-rating-form/component.js

If a user stops the survey mid-way and logs in again to finish, they should see their answers from before.
- Include session.expData in `currentFrameConfig` (which gets included with the default params passed to the exp-frame)
- Pass computed properties into the exp-frame
- Define a setter for the `responses` computed property of the `exp-overview` and `exp-rating-form` frames so that the questions are updated with the passed in data.
- Add a flag `loadData` to easily enable/disable loading existing data (Requires https://github.com/CenterForOpenScience/isp/pull/66 to get merged) 
Holding off on defining a setter for the `exp-card-sort` `responses` computed until https://github.com/CenterForOpenScience/exp-addons/pull/131 is merged

Feature: De-serialize form data [LEI-194]

---

exp-player/addon/components/exp-overview/component.js
exp-player/addon/components/exp-rating-form/template.hbs

Fix showing optional questions on the exp-overview and exp-rating-form frames.

Fix showing optional questions

---

exp-player/addon/components/exp-card-sort/component.js

Refs: https://openscience.atlassian.net/browse/LEI-216
Instead of serializing card-sort data into the format: `{bucket0: [card1, card2, card3...]}`
change it to `{card1: 0, card2: 0, card3: 0, ...}`
- Change `meta.data.properties` & `responses` computed

Fix card-sort serialization [LEI-216]

---

exp-player/addon/components/exp-free-response/template.hbs
exp-player/addon/components/exp-overview/template.hbs

Refs: https://openscience.atlassian.net/browse/LEI-223
Ensure progress bars placement is consistent across forms
On the overview and free-response forms, move the progress bar below the previous/continue buttons.

Move progress bar below previous/continue buttons [LEI-223]

---

exp-player/addon/components/exp-rating-form/component.js
exp-player/addon/components/exp-rating-form/template.hbs

Refs: https://openscience.atlassian.net/browse/LEI-222
On the `exp-rating-form`, consolidate `nextPage` and `continue` actions to reduce repetition in the template.

Consolidate nextPage and continue actions [LEI-222]

---

exp-player/addon/components/exp-overview/component.js
exp-player/addon/components/exp-rating-form/component.js

Refs: https://openscience.atlassian.net/browse/LEI-217
Companion to: https://github.com/CenterForOpenScience/isp/pull/72
Since the translation strings for numbers will be just the number (e.g. "0" instead of
"number0"), use integers in the options scales so that those values are serialized as integers.
Requires changes in https://github.com/CenterForOpenScience/isp/pull/72

Use integers for options [LEI-217]

---

exp-models/addon/adapters/application.js
exp-models/addon/models/account.js

Refs: https://openscience.atlassian.net/browse/LEI-219
Companion to: https://github.com/CenterForOpenScience/lookit/pull/62
The username field is available on records as a convenience, but it is not canonical, and not every record in the database provides a value for it. (some specify null, others omit the field entirely)
We will replace this less-reliable field with a computed property, calculated from the record id: `namespace.collection.shortId` --> `shortId`.
(this calculation is already done in the serializer, but we'll keep the separate property for readability, and in case the serializer changes in the future)
Deprecate the standalone username field in the model. Any existing `attributes.username` values will be ignored.
Replace this with a computed property that calculates …

Change username to computed property

---

exp-models/addon/models/account.js
exp-player/addon/randomizers/pref-phys-pilot.js
exp-player/tests/unit/randomizers/pref-phys-pilot-test.js

Refs: https://openscience.atlassian.net/browse/LEI-233
Companion to: 
Change the rules for how "previous session" is chosen in the counterbalancing randomizer for Lookit preferential physics study.

Randomizer improvements

---

exp-models/addon/components/jam-auth/component.js
exp-models/addon/components/jam-auth/template.hbs

Refs: https://openscience.atlassian.net/browse/LEI-238
Companion to: https://github.com/CenterForOpenScience/isp/pull/77
Button is now also disabled if the invalidAuth modal is open.
- Add `disabled` computed to replace logic in the template
- Button is now also disabled if the `invalidAuth` modal is open (prevents flashing disabled --> enabled). When the user dismisses the modal, the button will be enabled and they will be able to re-submit the form with a correct username & password.

Add computed for disabling login button [LEI-238]

---

exp-player/addon/components/exp-rating-form/component.js
exp-player/addon/components/exp-rating-form/template.hbs
exp-player/addon/styles/components/exp-rating-form.scss
exp-player/addon/styles/components/isp-radio-group.scss

Refs: https://openscience.atlassian.net/browse/LEI-241
Add in another optional question under question 10 on the rating-form, below "What aspect are you trying to change?"
- Add rating form question that only shows up when a user answers "yes" to question 10:  
- Adjust spacing on question four so that there is less space between the question and answer options:  
- I noticed the question's wording seems incorrect so I asked for clarification (but that change would occur in `translations.js`

Feature/add rating question [LEI-241]

---

exp-models/addon/components/jam-auth/component.js
exp-models/addon/models/session.js
exp-player/addon/randomizers/pref-phys-pilot.js
exp-player/addon/services/video-recorder.js

Refs: https://openscience.atlassian.net/browse/LEI-245
Minor cleanup found while working on login ticket.
- Login now sends the exact username and password as typed. It does not try to remove characters (eg leading/trailing spaces). This should be more consistent with how JamDB login works.
- Fix malformed markup in video widget
- Minor automated syntax reformatting

Send passwords to server as written and other tweaks

---

exp-player/addon/components/exp-rating-form/component.js

Refs: https://openscience.atlassian.net/browse/LEI-254
On the exp-rating-form component, make the progressBarPage computed watch 'framePage'
as there is no 'currentPage' attribute.

Make progressBarPage watch 'framePage' [LEI-254]

---

exp-player/addon/components/exp-exit-survey-pilot.js
exp-player/addon/components/exp-exit-survey.js
exp-player/addon/styles/addon.scss
exp-player/addon/templates/components/exp-exit-survey-pilot.hbs
exp-player/addon/templates/components/exp-exit-survey.hbs

Refs: https://openscience.atlassian.net/browse/LEI-249
Companion to: TBD (will need to update Lookit submodule commit)
Improve the experiment exit survey.
- ~~Fix "Number sessions completed" indicator to filter by completed flag (moved to separate ticket)~~
This affects the last frame (exit survey) when completing a study.
To test locally, you can change code to make the study run faster. See JIRA ticket for notes on what variables to modify.

Confirmation dialog when user withdraws their data

---

exp-models/addon/models/session.js
exp-player/addon/components/exp-player.js
exp-player/index.js

Refs: https://openscience.atlassian.net/browse/LEI-248
Companion to: TBD
If a user leaves a study early, capture event information.
- Add some default feature flag settings to `config()` for addon, so that non-ISP apps don't break when trying to consume code intended for ISP.
- Add flags/timing events for early exit so a record is saved in the session (see testing notes)
- When user hits F1 key
- When user leaves the page manually via back button, eg beforeunload events
- Minor code reformatting and cleanup
This adds a new field, `globalEventTimings`, to the attributes section of a session payload.
Any attempt to exit the study early should yield an `exitEarly` eventType. The type of the exit can be either:
- *browserNavigationAttempt*: Back button, close window, etc.
- *manualInterrupt*: …

[rfr] Flags and timing events for various kinds of early exit

---

exp-player/addon/components/exp-player.js

Refs: https://openscience.atlassian.net/browse/LEI-267
Companion to: 
The player currently has certain custom behaviors that are Lookit-specific. We do not, for example, want ISP users to be able to skip to the last frame by pressing F1.
Refactor to move those behaviors inside lookit.
- Reorg code: move lookit-only functionality into Lookit.
- Add a new `beforeUnload` hook to the player, controlling additional custom behavior that happens when a user leaves. For example, it can be used to display a toast message with more info
- Add a new `messageEarlyExitModal` property, controlling text of the confirm-on-exit modal. (may not show this text in all browser, but method has to return a non-null value if you want the modal to appear)
- All studies will show warning messages with unsaved data …

Refactor player to extract Lookit-specific exit behaviors

---

exp-models/addon/authenticators/jam-jwt.js

Refs: https://openscience.atlassian.net/browse/LEI-270
Companion to: https://github.com/CenterForOpenScience/isp/pull/88
Get rid of spammy "getOwner" deprecation warnings in the console, by upgrading to newest ember-simple-auth version.
- Make changes to authenticator so that we don't get `.then/.catch undefined` errors when using the new ember-simple-auth version.
These errors previously came from login.js in the ISP app:
`login.js:21 Uncaught TypeError: this.get(...).authenticate(...).then(...).catch is not a function(…)`
- Try to login with a real account. It should work.
- Try to login with a fake account. It should not work, and the page should respond correctly. There should be no console errors or weird problems.

Update ember-simple-auth to avoid deprecation warnings

---

exp-player/addon/components/exp-player.js
exp-player/addon/components/exp-video-physics.js
exp-player/addon/services/video-recorder.js

Refs: https://openscience.atlassian.net/browse/LEI-265
Companion to: 
Fix an issue where user could not see the exit survey if they attempted to leave during the "fix camera configuration" screen.
Also, log event timings for these events. This entails saving *partial* frame payloads if a user has to exit early. This will require some internal refactoring to support the ISP use case on the shared platform, followed by a round of internal refactoring.
If you remove the "remember me" setting, it's much easier to see camera issues. (Lookit doesn't work *unless* "remember me" is selected)
To generate some test data for the target problems:
Make the browser forget authorization to access camera (must approve both browser and flash plugin settings). Authorize for the consent screen, but don't …

Improve log and exit experience when user exits study due to video issues

---

exp-player/addon/components/exp-overview/component.js
exp-player/addon/components/exp-overview/template.hbs
exp-player/addon/components/isp-radio-group/component.js
exp-player/addon/components/isp-radio-group/template.hbs
exp-player/addon/styles/addon.scss
exp-player/addon/styles/components/exp-overview.scss
exp-player/addon/styles/components/isp-radio-group.scss

Refs: https://openscience.atlassian.net/browse/LEI-263
- Add labels to the radio-button questions on the `exp-overview` form
- Add "I prefer not to answer" option to "On a scale from 1-10, how religious are you?"

Add labels to overview form radio questions [LEI-263]

---

exp-player/addon/components/exp-thank-you/template.hbs
exp-player/addon/styles/components/exp-thank-you.scss

Refs: https://openscience.atlassian.net/browse/LEI-278
Since the btn class no longer has a margin-bottom of 15px, the two buttons on the "thank you" page had no space between them. 
Add a bottom margin to the exit button on the "thank you" page so that there is space between that button and the "see results" button.

Add bottom margin to exit button [LEI-278]

---

exp-player/addon/components/exp-free-response/component.js
exp-player/addon/components/exp-free-response/template.hbs

Refs: https://openscience.atlassian.net/browse/LEI-262
- Make the power-select width smaller (currently takes up the full width of the page)
- Handle case where no time is selected (can happen if validation is turned off for testing)

Feature/fix time dropdown [LEI-262]

---

exp-models/addon/models/account.js
exp-player/addon/components/exp-exit-survey-pilot.js
exp-player/addon/components/exp-exit-survey.js

Refs: https://openscience.atlassian.net/browse/LEI-259
Mark study complete when user finishes exit survey, rather than when user clicks Return to Lookit at the final progress bar screen.
This is slightly more accurate and intuitive.
Before the change: complete an experiment, and then complete an exit survey. No data should be saved when moving from survey to progress bar/ thank you screen.
After the change: data should be saved in that step, and `session.completed` should change from false to true.

[WIP] Mark study complete sooner in Lookit exit workflow

---

exp-player/package.json

Blocker for: https://openscience.atlassian.net/browse/LEI-266
Companion to: https://github.com/CenterForOpenScience/lookit/pull/68/files
Fix regeneratorRuntime errors in Lookit.
Installing ember-power-select as a dependency added a (nonworking) version to every app that consumed exp-player.  Instead, this change makes the consuming app responsible for installing power-select directly (if it needs it), or not installing it, as appropriate.
- Move power select from dependencies to dev-dependencies. Light testing on ISP and Lookit.
- We will need to add ember-power-select as a dependency to experimenter.
- Checklist: both Lookit and ISP applications should build when restarting server/ after running npm install, the dropdown should work, and no regeneratorRuntime errors in console.

Make consuming apps responsible for installing ember power select

---

exp-player/addon/components/exp-overview/component.js

Refs: https://openscience.atlassian.net/browse/LEI-286
Add the option "I prefer not to answer" to the question "Do you follow a religion?" on the overview form:

Add preferNoAnswer option to religion yes/no question [LEI-286]

---

exp-player/addon/components/exp-video-physics.js
exp-player/addon/components/exp-video-preview.js

Refs: https://openscience.atlassian.net/browse/LEI-300
With schema validation now turned on correctly, JamDB was rejecting frames defined with `required: []`, causing things to fail saving that previously worked. This is a syntax issue that always existed but was exposed by another recent bugfix.
If a frame specifies the required attribute, it must be an array with at least one element:
http://json-schema.org/latest/json-schema-validation.html#anchor61
When no fields are required, we will omit it for now, pending a larger rewrite of the "automatic schema generation" feature down the line.
- Removed the "required" attribute from frames with no requirements.
Try saving an experiment such as:
http://localhost:4201/experiments/58178a2b3de08a007fc5989c/edit
Before the change it failed with …

Fix schema errors when saving experiments

---

exp-player/addon/components/exp-card-sort/template.hbs
exp-player/addon/styles/components/exp-card-sort.scss
exp-player/addon/styles/components/isp-radio-group.scss

Refs: https://openscience.atlassian.net/browse/LEI-282
Check the formatting of labels, questions, etc. using a pseudo-translation (double each translation string) to identify places where the UI may look off with long translation strings.
- Wrap bucket labels that are too long so that they do not overlap another label
- Put bucket labels into a separate row so that the buckets can stay aligned even
when the labels are of differing lengths
- Hide the label row on xs screens, because the row will collapse and list all of the labels and
then all of the buckets.
- Show the bucket labels inside the bucket row on xs screens so that the labels appear directly   above the bucket.
- Set a max-width for isp-radio-component buttons so that the text wraps onto multiple lines instead of increasing the …

Fix CSS for long translations [LEI-282]

---

exp-player/addon/components/exp-free-response/component.js

Refs: https://openscience.atlassian.net/browse/LEI-301
The first question on the exp-free-response frame was not getting deserialized correctly (the stored value is the 24hr time, but the options are objects containing keys for the time in 12hr and 24hr notation.
In `loadData`, check which option in `times` corresponds to the saved `24hr` time and set `EventTime` to that option.
Answer the first question on the exp-free-response frame about what time the situation occurred. Click "Continue" to advance to the next frame, then click "Previous Page" to return to the free-response page. Check to see that the answer to the first question is still selected.

Fix eventTime question deserialization [LEI-301]

---

exp-player/addon/components/exp-card-sort/component.js
exp-player/addon/components/exp-card-sort/template.hbs

Refs: https://openscience.atlassian.net/browse/LEI-302
If a user sorts cards on the cardsort1 page, then clicks the "Previous Page" button to
go to the previous page, and then clicks the "Continue" button to go back to the cardsort1 page, they should see 90 cards at the top to be sorted and three empty buckets to sort them into. Instead, the buckets still contain the previously sorted cards. 
When a user clicks the "Previous Page" button on the cardsort1 page, clear the sorted cards.
Steps to reproduce: 
1. On the first cardsort page, sort at least one card. Notice the number of cards left decreases. 
2. Click the "Previous Page" button
3. Click the "Continue" button to return to the cardsort page
4. Notice that the number of cards left is 90, but the sorted cards still re-appear.

Clear unsaved cardsort1 data [LEI-302]

---

exp-player/addon/components/exp-frame-base.js
exp-player/addon/components/exp-overview/component.js
exp-player/addon/components/select-input/template.hbs

Refs: 
- https://trello.com/c/cwBpdYLi/5-edge-case-overview-background-form-if-user-fills-out-form-but-then-changes-age-gender-residence-to-default-please-select-they-ar
- https://openscience.atlassian.net/browse/LEI-306
- Fix `Assertion Failed: You must use Ember.set() to set the value property` that prevents users from advancing to free-response form after clicking "Continue" on the overview form. 
- Fix issue where `loadData` gets called after changing the value of a question, overwriting the new value (e.g. when clicking "Previous Page" to return to the overview form from the free-response form, changing a select question back to "Please Select" would not make the "Continue" button disabled because the value was getting overwritten with the previous, valid value)
- Use `Ember.set()` …

Feature: fix select validation [LEI-306]

---

exp-player/addon/styles/components/exp-card-sort.scss

Refs: https://trello.com/c/e5LbqRT8/4-text-on-cards-in-sub-categories-runs-off-card
On small screen widths, card text runs off of cards.
- Make buckets wider
- Make cards wider
- Make card text break in between long words

Fix card text overflowing card

---

exp-models/addon/mixins/bulk-adapter.js
exp-models/addon/mixins/jam-document-adapter.js

Refs: https://openscience.atlassian.net/browse/LEI-305
Companion to: https://github.com/CenterForOpenScience/experimenter/pull/120
Experimenter should allow batch creation of records. This adds custom headers to requests where appropriate.
To be written

[rfr] Create batch contributors as a bulk operation

---

exp-models/addon/models/collection.js

Refs: https://openscience.atlassian.net/browse/LEI-313
Companion to: https://github.com/CenterForOpenScience/experimenter/pull/126
Fix an issue where saving collections permissions via ember broke the ability to log in.
(Ember was dropping the undocumented `plugins` field required for the accounts collection to work, as discovered in companion PR testing)
Add a plugins field to the collection serializer
See companion ticket.
For now we only need to save the `accounts` collection in ember- PATCH requests to the server for this endpoint are a limited use case. We may dig farther in the future as we add special permissions for other collections.

Fix collection bug that breaks ability to log in via Jam auth

---

exp-models/addon/services/store.js
exp-models/app/services/store.js

Refs: https://openscience.atlassian.net/browse/LEI-313
Companion to: 
Provide a helper method to depaginate the API.
We don't want to use this very often, but there are some specific use cases- particularly centered around exporting results for site administrators.
- Experimenter "all data" page
- Lookit "all sessions" (questionable; we should just redesign the page)
- ISP "who completed my study"
- Extend the store with a custom helper method. Limited initial support for options to control the request (eg what page to start from)- the ability to configure this has not been extensively tested.
- See usage example in companion PR.

"Query everything" helper for store

---

.travis.yml
exp-models/package.json
exp-player/addon/components/exp-rating-form/component.js
exp-player/package.json

Refs: https://openscience.atlassian.net/browse/LEI-332
Companion to: N/A fix
Question was missing from item 13 in exp-rating-form
1-liner addition to exp-rating-form
There should be 5 questions under "11. Please rate the extent to which you agree or disagree with the following statements:"
The last of which should be "Most people are trustworthy."

Add missing fields to exp-rating-form [LEI-332]

---

exp-models/addon/utils/csv-writer.js
exp-models/tests/unit/utils/csv-writer-test.js

Companion to: CenterForOpenScience/experimenter#129
Changes csv-writer util to output an empty string `''` instead of `'null'`
csv-writer and test
JSON null should be an empty string

Update csv-writer to use a blank value for JSON null type

---

exp-models/addon/models/experiment.js

Refs: https://openscience.atlassian.net/browse/LEI-275
Companion to: TBD
Address error where attributes were not available on prototype in Lookit production builds (though they were available in debug mode builds)
This removes blockers for Lookit, Experimenter, and ISP apps to deploy in production mode.
- Make `expStates` available as an enum when no instance is available (useful for Lookit queries)
Primary testing for this PR will be done as used with LEI consuming apps.

Production site should build in production mode

---

exp-player/addon/styles/components/exp-overview.scss

Refs: https://openscience.atlassian.net/browse/LEI-296
Companion to: will update ISP submodule reference after merge
Fixes "Average" label positioning for question 5
CSS only fix for the exp-overview scss file
The average label on should be positioned between 5 and 6 above the radio buttons

Fix average label positioning

---

exp-models/addon/mixins/jam-document-adapter.js

Refs: https://openscience.atlassian.net/browse/LEI-345
Companion to: https://github.com/CenterForOpenScience/isp/pull/123
When Jam fails due to invalid or expired tokens, in some cases it returns a 403. At present, we don't have a "repair" mechanism if a user gets logged out mid-study; thus the appropriate response to a 401 or 403 is to invalidate the session. Consuming apps can then decide how to handle that invalidation- usually by kicking the user back to the login page and wiping any state from memory. (hard reload)
See: https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/data-adapter-mixin.js#L122
See above
See companion PR

Invalidate session on 403 error

---

exp-player/addon/components/exp-card-sort/component.js
exp-player/addon/components/exp-frame-base/component.js
exp-player/addon/components/exp-free-response/component.js
exp-player/addon/components/exp-overview/component.js
exp-player/addon/components/exp-overview/template.hbs
exp-player/addon/components/exp-player/component.js
exp-player/addon/components/exp-player/template.hbs
exp-player/addon/components/exp-rating-form/component.js
exp-player/addon/components/exp-rating-form/template.hbs
exp-player/addon/components/exp-thank-you/component.js
exp-player/addon/components/isp-radio-group/component.js
exp-player/addon/components/isp-radio-group/template.hbs

Refs: https://openscience.atlassian.net/browse/LEI-344
https://openscience.atlassian.net/browse/LEI-344
Companion to: https://github.com/CenterForOpenScience/isp/pull/124
Some ISP components need to be RTL-aware, so that things like radio buttons can be drawn in the correct order.
This adds an `extras` field to the `exp-player` to support application-specific customization. ISP uses it to pass `isRTL` to individual components which can act on it as necessary.
Components are intended to be isolated, so use of `controllerFor` would be frowned on.
Use a custom exp-player field to pass information about RTL language configuration to the radio button renderer.
If no config is specified, then display the labels in the normal order.
See companion PR.
Try it with both lookit and ISP.

When using rtl language, display radio buttons in different order

---

exp-player/addon/components/exp-overview/template.hbs
exp-player/addon/components/exp-rating-form/template.hbs
exp-player/addon/components/isp-radio-group/component.js
exp-player/addon/components/isp-radio-group/template.hbs

Refs: https://openscience.atlassian.net/browse/LEI-344
Companion to:  TBD
Simplify RTL implementation, and ensure that hebrew site is laid out correctly (right aligned)
All text and buttons should be right-aligned for hebrew site
tbd

Simplified RTL support + fixes

---

exp-player/addon/components/exp-card-sort/component.js
exp-player/addon/components/exp-card-sort/template.hbs

Refs: https://openscience.atlassian.net/browse/LEI-350
Companion to: https://github.com/CenterForOpenScience/isp/pull/129
Make the card sort form reflect RTL settings. In particular, in an RTL language such as hebrew, the three and nine cat elements should be arranged favorable-->unfavorable- and the serialized responses should still match the specified categories that each card was dropped into.
- Change visual layout of card sort form, if RTL language is detected
- Change serialization mechanism to put things in the correct order regardless of the visual layout of the page.
- Do the study in english. Card sort labels should run left to right. (uncharacteristic -- > characteristic)
- Do the study in hebrew. Labels should run the other direction, as far as you can tell. (characteristic--> …

Further RTL support: misc pages and card sort UI 

---

exp-player/addon/components/exp-overview/component.js

Refs: https://openscience.atlassian.net/browse/LEI-364
Companion to: (tbd: pair with experimenter + ISP releases)
Fix an issue that prevented data from being saved when users completed the study on the production server.
This issue stems from the fact that the rules for datatypes had changed, but the staging server was grandfathered in under old rules- unless an experiment is saved via the experimenter edit view, the jamdb validation schema does not get updated.
Fix fields where validation was found not to match the actual new datatypes.
The ISP experiment is composed of the following frames. I have reviewed the validation rules for the following:
"overview",  - has validation, updated
"free-response", - has validation, appears valid
"card-sort",  - no special validation serverside …

Fix issues that prevented data from being saved

---

exp-player/blueprints/exp-frame/files/addon/components/__name__/component.js

Refs: https://openscience.atlassian.net/browse/LEI-362
Fix an issue where frames defined using the `exp-frame` blueprint did not work.
Blueprint broke when we moved to pod-style components. Make sure it imports the JS from the correct place.
The blueprint can be triggered as follows:
`ember generate exp-frame exp-something`
1. Make a new frame locally.
2. Using a version of experimenter with that new frame, try to define an experiment that contains an unrecognized frame. Confirm it fails in the experiment editor window in experimenter.
3. Try to define an experiment that uses the new frame. Confirm it works and displays correctly when you try to run that experiment. (preview mode etc)

Update blueprint to reflect move to pod style components

---

exp-player/addon/components/exp-frame-base-unsafe/component.js
exp-player/addon/components/exp-frame-base/component.js
exp-player/addon/components/exp-player/component.js
exp-player/addon/components/exp-video-preview/component.js
exp-player/addon/components/isp-radio-group/component.js
exp-player/addon/mixins/full-screen.js
exp-player/addon/mixins/media-reload.js
exp-player/addon/mixins/video-record.js
exp-player/addon/randomizers/next.js
exp-player/addon/randomizers/pref-phys-pilot.js
exp-player/addon/randomizers/pref-phys.js
exp-player/addon/randomizers/random.js
exp-player/addon/randomizers/rotate.js
exp-player/addon/randomizers/shuffle.js
exp-player/addon/services/video-recorder.js
exp-player/addon/utils/parse-experiment.js
exp-player/addon/yuidoc-prose.js
exp-player/package.json
exp-player/yarn.lock
exp-player/yuidoc.json

Refs: https://openscience.atlassian.net/browse/LEI-377
Add the ability to create auto-generated text documentation, especially for user-facing frames.
Add YUIDoc configuration and build commands. Add a demonstration of recommended practices for documenting three components:
- The base frame
- One frame that inherits the base, without changing input parameters or serialized data
- One frame that inherits the base, and changes both input parameters and serialized data
Also improve existing documentation to the minimum standard needed for it to show up in generated docs and build correctly. 
YUIDoc is based solely on the docstrings you give it. If you omit a docstring, a method won't appear in the docs. If you use annotate a method as a property, it will go with what you tell it.
It will …

[rfr] Sample YUIDoc boilerplate
