CenterForOpenScience/exp-addons

exp-models/.editorconfig, exp-player/.editorconfig
=> Enforce COS code style in editorconfig

exp-models/addon/mixins/jam-document-adapter.js, exp-models/addon/models/experiment.js, exp-player/addon/components/exp-consent.js, exp-player/addon/components/exp-dynamic-form.js, exp-player/addon/components/exp-frame-base.js, exp-player/addon/components/exp-player.js, exp-player/addon/templates/components/exp-dynamic-form.hbs, exp-player/app/components/exp-dynamic-form.js, exp-player/bower.json, exp-player/package.json
Supports https://github.com/CenterForOpenScience/experimenter/pull/26
=> Experiment Detail Page

exp-models/addon/adapters/session.js, exp-models/addon/mixins/jam-document-adapter.js, exp-models/addon/mixins/jam-document-serializer.js, exp-models/addon/mixins/jam-serializer.js, exp-models/addon/models/account.js, exp-models/addon/models/experiment.js, exp-models/addon/models/history.js
Refs https://openscience.atlassian.net/browse/LEI-78
See detailed notes on companion PR, https://github.com/CenterForOpenScience/experimenter/pull/31
=>  [WIP] (models) Use different sessions collection per experiment

exp-models/addon/mixins/jam-document-adapter.js, exp-models/addon/models/experiment.js, exp-player/addon/components/exp-consent.js
Companion PR for: https://github.com/CenterForOpenScience/experimenter/pull/32
=> More experiment detail

exp-player/addon/components/exp-player.js
Refs https://openscience.atlassian.net/browse/LEI-57 and https://openscience.atlassian.net/browse/LEI-30
Companion to https://github.com/CenterForOpenScience/experimenter/pull/35
See companion PR for description and changelog.
=> Player data flow and prompt user before exiting the page

exp-player/addon/components/exp-frame-base.js, exp-player/addon/components/exp-video.js, exp-player/addon/templates/components/exp-video.hbs, exp-player/app/components/exp-video.js, exp-player/tests/integration/components/exp-video-test.js
Refs https://openscience.atlassian.net/browse/LEI-82
Companion to https://github.com/CenterForOpenScience/experimenter/pull/37 ; see that PR for full description.
=> Add video player component

exp-models/addon/models/session.js, exp-player/addon/components/exp-audioplayer.js, exp-player/addon/components/exp-frame-base.js, exp-player/addon/components/exp-player.js, exp-player/addon/templates/components/exp-player.hbs, exp-player/addon/utils/parse-experiment.js, exp-player/app/utils/parse-experiment.js, exp-player/tests/unit/utils/parse-experiment-test.js
Refs https://openscience.atlassian.net/browse/LEI-89
Companion to https://github.com/CenterForOpenScience/experimenter/pull/41
See companion PR for full description.
=> Prototype random frame (player) 

exp-models/addon/authenticators/jam-osf-jwt.js, exp-player/addon/components/exp-lookit-overview.js, exp-player/addon/templates/components/exp-lookit-overview.hbs, exp-player/addon/templates/components/exp-player.hbs, exp-player/app/components/exp-lookit-overview.js
Adds the exp-lookit-overview frame for the exp-player
Also some misc cleanup:
- DRY the jam-osf-jwt authenticator and handle 500s when trying to authenticate
=> Add exp-lookit-overview

exp-models/addon/models/experiment.js, exp-player/addon/components/exp-player.js, exp-player/addon/components/exp-video.js, exp-player/addon/mixins/full-screen.js, exp-player/addon/templates/components/exp-player.hbs, exp-player/app/styles/app.css, exp-player/tests/unit/mixins/full-screen-test.js
Refs https://openscience.atlassian.net/browse/LEI-98
Companion to https://github.com/CenterForOpenScience/experimenter/pull/49
=> Put experiment in fullscreen mode (player)

exp-player/addon/components/exp-exit-survey.js, exp-player/addon/components/exp-video-config.js, exp-player/addon/components/exp-video-consent.js, exp-player/addon/mixins/media-reload.js, exp-player/addon/services/video-recorder.js, exp-player/addon/utils/parse-experiment.js
Refs https://openscience.atlassian.net/browse/LEI-105
Companion to https://github.com/CenterForOpenScience/experimenter/pull/53
=> Add a very simple random-shuffle choice frame (player)

exp-player/addon/components/exp-video.js, exp-player/addon/mixins/full-screen.js, exp-player/addon/templates/components/exp-player.hbs, exp-player/app/styles/app.css
Refs https://openscience.atlassian.net/browse/LEI-106
Improve fullscreen capabilities. Add styling for firefox, and make videos take up entire screen.
- Fix merge-related regression so that removed code stays removed
- Fix merge-related regression where change in variable name capitalization prevented "return to fullscreen" button from hiding when necessary
- Videos should take up the entire screen, and always auto-forward when done playing.
=> Fullscreen enhancements

exp-models/addon/models/experiment.js
When an experiment record loads and it has a thumbnailId, eagerly load
the thumbnail record. Once loaded, that record is cached behind the
'thumbnail' computed.
If the thumbnailId is not set, a new record needs to be created when
trying to set the thumbnail, and the experiment record needs to be
updated with the new thumbnailId
=> Better experiment.thumbnail getting/setting

exp-models/addon/models/experiment.js
So consuming code can check if the session collection gets created properly
=> Expose experiment._sessionCollection

exp-models/addon/models/session.js
Refs https://openscience.atlassian.net/browse/LEI-133
Companion to https://github.com/CenterForOpenScience/experimenter/pull/73
=> Add completed field to session model

exp-models/addon/authenticators/jam-osf-jwt.js
Refs https://openscience.atlassian.net/browse/LEI-117
Companion to https://github.com/CenterForOpenScience/experimenter/pull/69
=> Do not allow login unless user has namespace permissions

exp-models/addon/models/experiment.js, exp-models/addon/utils/constants.js, exp-models/app/utils/constants.js, exp-models/tests/unit/utils/constants-test.js
Refs: https://openscience.atlassian.net/browse/LEI-122
Companion to: https://github.com/CenterForOpenScience/experimenter/pull/79
=> Prevent writing to sessions when experiment inactive.

exp-player/addon/components/exp-video-consent.js, exp-player/addon/components/exp-video-record.js
=> Add videoId to the data of video recording frames

exp-player/addon/components/exp-player.js, exp-player/addon/templates/components/exp-lookit-overview.hbs, exp-player/addon/templates/components/exp-video-consent.hbs, exp-player/addon/templates/components/exp-video-setup.hbs
=> Styling updates

exp-player/addon/services/video-recorder.js
=> Force videos recording sessions to be at least 1.5 seconds

exp-models/addon/models/session.js
Refs: https://openscience.atlassian.net/browse/LEI-149
Companion to: https://github.com/CenterForOpenScience/experimenter/pull/84
=> Anonymize profile IDs displayed in result summary table

exp-models/addon/models/session.js, exp-player/addon/components/exp-mood-questionnaire.js, exp-player/addon/components/exp-video-preview.js, exp-player/addon/mixins/exp-player-route.js, exp-player/addon/services/video-recorder.js
Refs: https://openscience.atlassian.net/browse/LEI-136
Companion to: https://github.com/CenterForOpenScience/experimenter/pull/83
=> Schema consolidation and cleanup (models)

exp-models/addon/adapters/application.js, exp-models/addon/mixins/jam-document-adapter.js, exp-models/addon/mixins/jam-document-serializer.js, exp-models/addon/mixins/jam-model.js, exp-models/addon/models/experiment.js, exp-player/addon/components/exp-frame-base.js
Refs: https://openscience.atlassian.net/browse/LEI-145
Companion to: 
[LEI-145]
=> [WIP] Use shortIds for all document primary keys

exp-models/addon/adapters/application.js, exp-models/addon/adapters/collection.js, exp-models/addon/mixins/jam-document-adapter.js
Refs: https://openscience.atlassian.net/browse/LEI-159
Companion to: https://github.com/CenterForOpenScience/experimenter/pull/89
=> Fix malformed ULRLs/ adapter error issues

exp-player/addon/components/exp-frame-base.js, exp-player/addon/components/exp-video-physics.js, exp-player/addon/components/exp-video-preview.js, exp-player/addon/randomizers/pref-phys.js, exp-player/addon/services/video-recorder.js, exp-player/addon/templates/components/exp-video-physics.hbs
Adding a PR here to test video recording on the staging server. I followed the video frame example.
=> Recording during exp-video-preview

exp-player/addon/components/exp-mood-questionnaire.js, exp-player/addon/templates/components/exp-mood-questionnaire.hbs
Refs: https://openscience.atlassian.net/browse/LEI-174
=> Add checks and conditional checks for all required fields, fix date bug

exp-player/addon/components/exp-player.js, exp-player/addon/templates/components/exp-player.hbs
Refs: https://openscience.atlassian.net/browse/LEI-173
Modal becomes pop up
=> change modal to just a warning popup

exp-player/addon/components/exp-player.js
F1 keypresses weren't getting fired by the keypress handler. Using keyup instead fixes this.
=> Exit press

exp-player/addon/components/exp-overview/component.js, exp-player/addon/components/exp-overview/template.hbs, exp-player/app/components/exp-overview.js, exp-player/package.json
Add the `overview-info-form` component from ISP to `exp-player` so that it is available to experimenter.
=> Make exp-frame for overview component

exp-models/addon/authenticators/jam-jwt.js, exp-models/addon/authorizers/jam-jwt.js, exp-models/app/authenticators/jam-jwt.js, exp-models/app/authorizers/jam-jwt.js, exp-player/addon/components/jam-auth/component.js, exp-player/addon/components/jam-auth/template.hbs, exp-player/app/components/jam-auth/component.js, exp-player/tests/integration/components/jam-auth/component-test.js
Add jam-auth component, authenticator & authorizer to exp-addons since it is used by both lookit and ISP
=> Add jam-auth code to exp-addons

exp-player/addon/styles/components/exp-video-consent.scss, exp-player/addon/templates/components/exp-exit-survey.hbs, exp-player/addon/templates/components/exp-video-consent.hbs
=> Fix centering of consent document & wording of reminder checkbox.

exp-player/addon/components/exp-rating-form/component.js, exp-player/addon/components/exp-rating-form/template.hbs, exp-player/addon/styles/addon.scss, exp-player/addon/styles/components/exp-rating-form.scss
Make questions on rating form easier to read
- Make rating form labels go onto two lines
- Make question font size larger and adjust spacing 
- Fix displaying optional question
=> Feature: Fix rating form UI

exp-player/addon/components/select-input/component.js, exp-player/addon/components/select-input/template.hbs, exp-player/app/components/select-input/component.js, exp-player/tests/integration/components/select-input/component-test.js
Move `select-input` component from ISP to exp-addons
=> Move select-input component to exp-addons

exp-player/addon/components/exp-frame-base.js, exp-player/addon/components/exp-player.js, exp-player/addon/components/exp-video-physics.js
=> exp-video-physics fixes

exp-player/addon/components/exp-thank-you/template.hbs
Add link to personality results page
=> Add link to personality results page

exp-player/addon/components/exp-thank-you/template.hbs
Redirect user to exit page when they hit "Exit" from the exp-thank-you component
Requires: https://github.com/CenterForOpenScience/isp/pull/50
=> Redirect user to exit page on exit [LEI-176]

exp-player/addon/randomizers/pref-phys-pilot.js
=> Correct objects used in stay/fall videos for Lookit pilot study

exp-player/addon/components/exp-physics-intro/component.js, exp-player/addon/randomizers/pref-phys-pilot.js, exp-player/addon/templates/components/exp-physics-intro.hbs
=> Add calibration videos and confirmation code for continued piloting

exp-player/addon/components/exp-overview/component.js
Refs: https://openscience.atlassian.net/browse/LEI-212
Companion to: https://github.com/CenterForOpenScience/isp/pull/69
Switch order of questions asking about religion:
=> Switch question order in overview form [LEI-212]

exp-player/addon/components/exp-rating-form/component.js, exp-player/addon/components/isp-radio-group/template.hbs, exp-player/addon/styles/components/isp-radio-group.scss
Refs: https://openscience.atlassian.net/browse/LEI-213
- Increase spacing of radio buttons in questions 2, 4, & 6
- Fix scales in questions 2, 6 & 9
=> Rating Form UI changes [LEI-213]

exp-player/addon/components/exp-rating-form/component.js
Refs: https://openscience.atlassian.net/browse/LEI-230
Move question 8 in the exp-rating form to the end and shift other questions up in terms of which page they should appear on.
=> Switch question order [LEI-230]

exp-player/addon/components/exp-card-sort/component.js, exp-player/addon/components/exp-card-sort/template.hbs, exp-player/addon/components/exp-free-response/component.js, exp-player/addon/components/exp-free-response/template.hbs, exp-player/addon/components/exp-overview/component.js, exp-player/addon/components/exp-overview/template.hbs, exp-player/addon/components/exp-rating-form/component.js, exp-player/addon/components/exp-rating-form/template.hbs
Refs: https://openscience.atlassian.net/browse/LEI-231
Companion to: https://github.com/CenterForOpenScience/isp/pull/76
Add the ability to turn validation off for testing.
If the `validate` flag is set to false, allow users to continue through the survey without having to answer every question.
=> Feature/validation flag [LEI-231]

exp-player/addon/components/exp-overview/component.js
Refs: https://openscience.atlassian.net/browse/LEI-244
- Make birth city & country two questions
- Update showOptional computed to track the optional question that is now at questions[9]
=> Split birth city & country into two questions [LEI-244]

exp-player/addon/components/exp-rating-form/component.js
Refs: https://openscience.atlassian.net/browse/LEI-232
Currently, validation is only working on the first `framePage` of the `exp-rating-form`. All validators on the other pages are disabled, but do not get re-enabled when the framePage changes.
Add validators for each page that depend on validators for questions on that page. Make allowNext track the page validators and framePage, and return whether the current page's validator is valid.
The `continue` button should be disabled until all of the questions on the page are answered. However, if the `config.validate` flag is `false`, all of the continue buttons should be enabled.
=> Fix rating form validation [LEI-232]

exp-player/addon/components/exp-card-sort/component.js, exp-player/addon/components/exp-frame-base.js, exp-player/addon/components/exp-free-response/component.js, exp-player/addon/components/exp-overview/component.js, exp-player/addon/components/exp-rating-form/component.js
Companion to: https://github.com/CenterForOpenScience/isp/pull/51
The feature flags were refactored in this [commit](https://github.com/CenterForOpenScience/isp/pull/51/commits/53adda78ee736ead0b7e76a4a5ae7c214f191d48) and need to be updated where they are used as well.
=> Update feature flags

exp-player/addon/components/exp-free-response/component.js, exp-player/addon/components/exp-free-response/template.hbs, exp-player/addon/components/exp-rating-form/component.js
Refs: https://openscience.atlassian.net/browse/LEI-262
- Replace the two different experiment conditions (describing a situation at 10am or 7pm) and ask the participant to describe an experience they remember well
- Exp-rating form question 3 now asks "Please rate your behavior in the situation you described."
=> Remove experiment conditions [LEI-262]

exp-player/addon/components/exp-rating-form/component.js
Refs: https://openscience.atlassian.net/browse/LEI-264
For the last question on the exp-rating-form, add the option "I prefer not to answer":  ![screen shot 2016-10-18 at 10 51 00 am](https://cloud.githubusercontent.com/assets/6414394/19483036/e562f09c-9520-11e6-858a-9ba5c12d0f77.png)
=> Add preferNoAnswer option to last measures question [LEI-264]

exp-player/addon/components/exp-card-sort/template.hbs, exp-player/addon/components/exp-free-response/component.js, exp-player/addon/components/exp-free-response/template.hbs, exp-player/package.json
Refs: https://openscience.atlassian.net/browse/LEI-262
Companion to: https://github.com/CenterForOpenScience/isp/pull/89
Add question asking participants approximately what time the situation they are describing began.
Use ember-power-select component for the drop-down to achieve the desired styling.
=> Add question asking time of situation [LEI-262]

exp-player/addon/components/exp-free-response/template.hbs, exp-player/addon/styles/addon.scss, exp-player/addon/styles/components/exp-free-response.scss
Refs: https://openscience.atlassian.net/browse/LEI-288
Bold and underline "Please describe an experience yesterday that you remember well. " in the free-response form instructions.
=> Bold & underline first sentence in free-resp instructions [LEI-288]

exp-player/addon/components/exp-rating-form/component.js
Refs: https://openscience.atlassian.net/browse/LEI-307
Companion to: https://github.com/CenterForOpenScience/isp/pull/105
Change language of measures question 8 (label and items)
=> Update measures question 8 [LEI-307]

exp-player/addon/components/exp-exit-survey/template.hbs
I'm very sorry this is coming late :( Doesn't need to get merged today/with this release, but if it's easy to sneak in soon that'd be great...
=> Minor wording change to exp-exit-survey

.travis.yml, README.md, exp-models/addon/utils/csv-writer.js, exp-models/app/utils/csv-writer.js, exp-models/ember-cli-build.js, exp-models/tests/unit/utils/csv-writer-test.js
Refs: https://openscience.atlassian.net/browse/LEI-246
Utility function for generating a CSV file from an array of objects
* Add csv-writer utility with tests
* Update travis and README
Run `npm link` in exp-models to ensure that the module is able to be referenced by name (instead of by path)
=> Add csv-writer

exp-models/addon/models/session.js
Refs: 
* https://openscience.atlassian.net/browse/LEI-317
* https://openscience.atlassian.net/browse/LEI-246
Companion to: CenterForOpenScience/isp#111
Need the extra field for ISP
Update to the session model
=> Add extra field [LEI-317]

exp-player/addon/components/exp-card-sort/template.hbs
Refs: https://openscience.atlassian.net/browse/LEI-327
Companion to: CenterForOpenScience/isp#115
See ISP PR
Move cards.length to count attribute for ember-i18n
See ISP PR
=> Move count to hbs attribute for translation/pluralization [LEI-327]

exp-models/addon/serializers/account.js
Refs: https://openscience.atlassian.net/browse/LEI-281
Companion to: CenterForOpenScience/experimenter#132
UI Responsiveness in account creation
Adds conditional check for encrypted password
=> Conditionally check for hashed password in serializer

exp-player/addon/components/exp-rating-form/component.js
Refs: https://openscience.atlassian.net/browse/LEI-372
Companion to: TBD
Add an "At work" question option to "To what extent do you think your life develops in the following environments?" question (14, second to last page of survey)
Add extra item at end
Second to last survey page.
Only a very few languages will support this initially (4), the other 15 currently available translations will be incomplete. The user should never have to experience something like the missing-text situation below:
=> Add question to survey

exp-player/addon/styles/components/exp-lookit-geometry-alternation.scss
Finalize code for geometry alternation study ahead of starting testing
Ready to be merged into develop branch & then pushed to production!
=> Final code for geometry study

exp-player/addon/randomizers/random-parameter-set.js
documentation-only update, should be final change before updating the posted yuidocs documentation
=> update yuidoc documentation for random-parameter-set randomizer
